### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by envil** [blove/angular-reactive-authentication#1]
I tried to run the app but got a lot of errors, couldn't serve it.

**Comment by blove** [comment]
@envil I apologize for the issues. I don't *think* I committed and pushed broken code, but it was certainly broken.

I have committed and pushed updates to the master branch to resolve the issues, primarily with Angular Material. Please note that this repo is still using NgRx 2/3, not the latest release, v4.

**Comment by envil** [comment]
It works now. Thank you!
